### ISSUE TITLE
GA script not being rendered properly

### ISSUE THREAD

**Issue by ekryski** [GitbookIO/plugin-ga#14]
For some reason this has been happening the last couple weeks.

![image](https://cloud.githubusercontent.com/assets/599019/20532849/b5538392-b098-11e6-8fca-609f9d51c9cd.png)

Any ideas @SamyPesse @AaronO?

**Comment by AaronO** [comment]
@ekryski I think that happens because you guys have some custom code/plugin, that goes over the last elements and sets `style="display: block"`, which the browser (to my surprise) applies.

**Comment by ekryski** [comment]
Yeah might be that. @daffl ended up fixing it by forking the plugin and making some mods. Thanks for the reply @AaronO!

**Comment by daffl** [comment]
As a reference, I submitted a PR with the fix to the upstream repository at https://github.com/rtCamp/gitbook-plugin-collapsible-menu/pull/4
