### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by bp-wu** [GitbookIO/plugin-ga#15]
Hi,

for some reason (and even though I've created the correct book.json), the plugin does not work - i can find my tracking code in the script settings, but Google Tag Assistant is only showing the original script of gitbook.com

My book.json:
{
   "plugins": ["ga"],
   "pluginsConfig": {
       "ga": {
           "token": "UA-72539203-1"
       }
   }
}

My book: manual.blackpilot.com

I have a multi-language site, could that be an issue?

Cheers

**Comment by nagim** [comment]
Additional infó: it seems that for the default page link, it does not work, however, it works if the direct build link is viewed.

**Comment by SimulatedGREG** [comment]
@SamyPesse 

I was just looking at my analytics and noticed a huge decline in overall views on November 15th. Also not seeing "Real-Time" viewers when I access the site myself. I'm pretty confident all my users did not just suddenly lose interest in [my gitbook](https://simulatedgreg.gitbooks.io/electron-vue/content/).

![image](https://cloud.githubusercontent.com/assets/8327811/20743516/7d5425a0-b69c-11e6-98b4-0c3ee7a85876.png)

Any ideas?

**Comment by bp-wu** [comment]
Hi, 

I was checking your page with the google tag assistant (chrome plugin) and I also just saw one tracking token (there should be two or more in my opinion). I have no idea how to fix this, maybe using the google tag manager plugin could work?

**Comment by AaronO** [comment]
@bp-wu @SimulatedGREG Can you guys give it a try now ?

I shipped a change that should remove the conflict.

**Comment by SimulatedGREG** [comment]
@AaronO 

We'll update back in a few days to let some data come in. So far the "Real-Time" section is working as expected now! 🎉

**Comment by bp-wu** [comment]
@AaronO 
Thanks a lot! Working well.

**Comment by SimulatedGREG** [comment]
Can also confirm things are back in order. Thank you @AaronO !
